apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
      - name: backend
         image: hashicorp/http-echo
      args:
       - "-text=Hello from Notes Backend 🚀"
      ports:
       - containerPort: 5678