apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-frontend-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>Notes App</h1>
      <input id="note" placeholder="Enter note"/>
      <button onclick="addNote()">Call Backend</button>
      <button onclick="getNotes()">Call Backend Again</button>
      <pre id="output"></pre>

      <script>
        function addNote() {
          fetch('/api/')
            .then(res => res.text())
            .then(data => {
              document.getElementById('output').innerText = data;
            });
        }

        function getNotes() {
          fetch('/api/')
            .then(res => res.text())
            .then(data => {
              document.getElementById('output').innerText = data;
            });
        }
      </script>
    </body>
    </html>